export const IMDE_DEMO_SCENARIO_ID = "imde-audit-findings-demo";

export const imdeDemoScenario = {
  demoScenarioId: IMDE_DEMO_SCENARIO_ID,
  title: "Audit Findings Prediction Sandbox",
  baseModelId: "hf-microsoft-deberta-v3-contractnli",
  requestDefaults: {
    name: "Audit findings prediction fine-tuning",
    description: "Governed team sandbox for findings prediction model tuning with approved demo transaction data.",
    workspaceTemplateId: "aml-team-standard-v1",
    sandboxType: "team" as const,
    dataPackages: ["transactions_training", "findings_gold"],
    computeProfile: "gpu-small" as const,
    durationDays: 30,
    costCenter: "AUDIT-AI-2026",
    businessJustification: "Tune and evaluate a findings prediction model using synthetic, de-identified transaction-testing demo data before marketplace publication.",
  },
  actors: {
    ownerId: "ds-priya-shah",
    ownerName: "Priya Shah",
    approverId: "platform-admin-morgan-lee",
    approverName: "Morgan Lee",
    teamName: "Assurance AI Lab",
  },
  dataPackages: [
    {
      id: "transactions_training",
      displayName: "Transaction Testing Dataset",
      version: "12",
      demoDataStatement: "synthetic, de-identified approved demo transaction data for audit model training.",
    },
    {
      id: "findings_gold",
      displayName: "Findings Gold Dataset",
      version: "4",
      demoDataStatement: "synthetic, de-identified approved demo findings outcomes for evaluation.",
    },
  ],
  selectedRunId: "run-findings-contractnli-v3",
  evaluationRuns: [
    {
      id: "run-findings-contractnli-v3",
      name: "ContractNLI findings classifier v3",
      status: "completed" as const,
      selectedWinner: true,
      governanceStatus: "ready-for-publish" as const,
      baseModelId: "hf-microsoft-deberta-v3-contractnli",
      dataPackages: ["transactions_training", "findings_gold"],
      metrics: { f1: 0.87, accuracy: 0.91, latencyMs: 142 },
      lineage: {
        notebookPath: "notebooks/findings_prediction_finetune.ipynb",
        templateId: "findings-prediction-finetune-v1",
        trainingDataVersion: "transactions_training:12",
        evaluationDataVersion: "findings_gold:4",
      },
    },
    {
      id: "run-findings-baseline-v1",
      name: "Baseline gradient boosted transactions classifier",
      status: "completed" as const,
      selectedWinner: false,
      governanceStatus: "in-review" as const,
      baseModelId: "baseline-transactions-gbdt",
      dataPackages: ["transactions_training", "findings_gold"],
      metrics: { f1: 0.74, accuracy: 0.82, latencyMs: 96 },
      lineage: {
        notebookPath: "notebooks/transactions_baseline_train.ipynb",
        templateId: "transactions-baseline-v1",
        trainingDataVersion: "transactions_training:12",
        evaluationDataVersion: "findings_gold:4",
      },
    },
  ],
  publishedExperience: {
    modelRouteId: "audit-findings-prediction-space",
    displayName: "Audit Findings Prediction Space",
    task: "Audit transaction findings prediction",
    trustStatus: "governance-passed" as const,
    experienceStatus: "published" as const,
  },
};