const demoAssetReviewFixture = {
  assetId: "asset-claims-triage-bundle",
  assetName: "Claims Triage Agent Bundle",
  publisher: "Contoso Health AI Studio",
  tenant: "Fabrikam Benefits Demo Tenant",
  requestedAction: "Publish to enterprise AI Asset Marketplace",
  submittedVersion: "1.4.0-submitted",
  remediatedVersion: "1.4.1-remediated",
  currentState: "needs_remediation",
  demoLabels: ["Submitted AI asset security review", "Local-only demo fixture", "Synthetic data"],
  reviewStates: [
    { id: "new", label: "New submission", decision: "Intake received" },
    { id: "in_review", label: "In security review", decision: "Scan running" },
    { id: "needs_remediation", label: "Needs remediation", decision: "Submitted version blocked" },
    { id: "rejected_submitted_version", label: "Rejected submitted version", decision: "Unsafe version cannot publish" },
    { id: "waived_by_reviewer", label: "Waived by reviewer", decision: "Accepted risk with reviewer reason" },
    { id: "approved_remediated_version", label: "Approved remediated version", decision: "Only the remediated version can publish" },
  ],
  requestedPermissions: [
    "Read claims queue and member case payloads",
    "Call LLM gateway for triage summaries",
    "Invoke MCP case-search, web-fetch, and shell-runner tools",
    "Write review recommendations to audit timeline",
  ],
  bundleInventory: [
    { surface: "Application source", path: "demos/atv-security-target/src", purpose: "Express, SQLite, LLM, and agent runtime" },
    { surface: "Browser UI", path: "demos/atv-security-target/public", purpose: "Reviewer-facing asset evidence console" },
    { surface: "MCP config", path: "demos/atv-security-target/.github/copilot-mcp-config.json", purpose: "Tool approval and fake secret fixture" },
    { surface: "Agents and skills", path: "demos/atv-security-target/.github", purpose: "Prompt-injection and broad-tool-scope fixtures" },
    { surface: "Editor settings", path: "demos/atv-security-target/.vscode/settings.json", purpose: "Workspace trust and auto-approval fixture" },
  ],
  provenance: {
    liveScan: "Live scan",
    seededFallback: "Seeded fallback",
    workbenchFixture: "Workbench fixture",
  },
  reportPaths: {
    seededFallback: "docs/security/fixtures/atv-security-target-seeded-fallback-report.md",
    optionalLive: "docs/security/YYYY-MM-DD-security-report.md",
  },
  goldenFindings: [
    {
      id: "ATV-MCP-001",
      title: "Unpinned and overbroad MCP execution",
      rule: "MCP-01",
      severity: "high",
      path: "demos/atv-security-target/.github/copilot-mcp-config.json",
      provenance: "Seeded fallback",
      businessRisk: "A submitted asset can request wildcard tool access and auto-approved secret reads before security review.",
      owner: "Platform Security",
      decision: "Block submitted version until MCP package version, tool allowlist, and approvals are scoped.",
    },
    {
      id: "ATV-HOOK-002",
      title: "Hook exfiltration-shaped automation",
      rule: "HOOK-02",
      severity: "high",
      path: "demos/atv-security-target/.github/hooks/scripts/post-tool-use.js",
      provenance: "Seeded fallback",
      businessRisk: "Tool output could be posted outside the review boundary if a similar hook were made active.",
      owner: "Agent Platform",
      decision: "Block submitted version; require hook removal or signed, reviewed telemetry destination.",
    },
    {
      id: "ATV-A01-003",
      title: "Broken authorization exposes member case data",
      rule: "OWASP-A01",
      severity: "critical",
      path: "demos/atv-security-target/src/routes/cases.js",
      provenance: "Seeded fallback",
      businessRisk: "Claims payloads can be read or approved without durable reviewer identity and ownership checks.",
      owner: "Asset Publisher",
      decision: "Reject submitted version for enterprise publication until access control is fixed and tested.",
    },
    {
      id: "ATV-A10-004",
      title: "SSRF and data exposure through web-fetch tooling",
      rule: "OWASP-A10",
      severity: "high",
      path: "demos/atv-security-target/src/mcp/tools.js",
      provenance: "Seeded fallback",
      businessRisk: "An agent tool can fetch attacker-chosen or internal URLs while handling claims context.",
      owner: "Asset Publisher",
      decision: "Block submitted version until URL allowlists and network egress controls exist.",
    },
    {
      id: "ATV-STRIDE-005",
      title: "Marketplace STRIDE synthesis requires remediation gate",
      rule: "STRIDE",
      severity: "medium",
      path: "demos/atv-security-target",
      provenance: "Workbench fixture",
      businessRisk: "Spoofing, tampering, repudiation, disclosure, DoS, and privilege escalation risks combine into a publication decision.",
      owner: "Security Reviewer",
      decision: "Needs remediation by default; waiver is accepted risk, not approval of the submitted version.",
    },
  ],
  syntheticEvidenceRegistry: [
    { value: "sk-proj-DEMO1234567890abcdefghijklmnopqrst", file: ".github/copilot-mcp-config.json", purpose: "Fake OpenAI-style key", category: "Secrets" },
    { value: "postgres://demo:demo-password@db.example.invalid:5432/claims", file: ".github/copilot-mcp-config.json", purpose: "Fake database URL", category: "Secrets" },
    { value: "Bearer demo-token-1234567890abcdefghijklmnop", file: ".vscode/settings.json", purpose: "Fake bearer token", category: "Secrets" },
    { value: "Password123!", file: "src/routes/auth.js", purpose: "Fake demo password", category: "Authentication failures" },
    { value: "https://example.invalid/audit", file: ".github/hooks/scripts/post-tool-use.js", purpose: "Non-routable webhook fixture", category: "Hook safety" },
    { value: "Alex Morgan", file: "src/db.js", purpose: "Synthetic member name", category: "Synthetic data" },
    { value: "M-100", file: "src/db.js", purpose: "Synthetic member identifier", category: "Synthetic data" },
  ],
}

module.exports = demoAssetReviewFixture